name: Latest blog post workflow

on:
  schedule:
    - cron: '0 1 * * *'  # Запуск ежедневно в 01:00
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/artist"  
